APP = $(notdir $(CURDIR))

MEANFIELD_MODEL = $(MEANFIELD_DIR)/meanfield_and_syn/models/meanfield_model_impl.c
MEANFIELD_MODEL_H = $(MEANFIELD_DIR)/meanfield_and_syn/models/meanfield_model_impl.h
PARAMS_FROM_NETWORK_H = $(MEANFIELD_DIR)/meanfield_and_syn/models/params_from_network.h
P_FIT_POLYNOMIAL_H = $(MEANFIELD_DIR)/meanfield_and_syn/models/P_fit_polynomial.h
MEANFIELD_IMPL_H = $(MEANFIELD_DIR)/meanfield_and_syn/implementations/meanfield_impl_standard.h
SYNAPSE_TYPE_H = $(MEANFIELD_DIR)/meanfield_and_syn/synapse_types/synapse_types_exponential_impl.h
SYNAPSE_DYNAMICS = $(MEANFIELD_DIR)/meanfield_and_syn/plasticity/synapse_dynamics_static_impl.c

include ../meanfield_not_only_build.mk
